[[plugins]]
repo = 'Shougo/deoplete.nvim'
on_event = 'InsertEnter'
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  inoremap <expr><Tab> pumvisible() ? "\<DOWN>" : "\<Tab>"
  inoremap <expr><S-Tab> pumvisible() ? "\<UP>" : "\<S-Tab>"
'''

[[plugins]]
repo = 'rust-lang/rust.vim'
on_ft = 'rust'
hook_add = '''
  let g:rustfmt_autosave=1
  let g:rust_doc#define_map_K=0
'''

[[plugins]]
repo = 'sebastianmarkow/deoplete-rust'
on_ft = 'rust'
depends = ['deoplete.nvim']
hook_add = '''
  let g:deoplete#sources#rust#racer_binary=expand('~/.cargo/bin/racer')
  let g:deoplete#sources#rust#rust_source_path=expand('~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src')
  let $RUST_SRC_PATH=expand('~/.rustup/toolchains/stable-x86_64-unknown-linux-gnu/lib/rustlib/src/rust/src')
  let g:deoplete#sources#rust#show_duplicates=1
  let g:deoplete#sources#rust#disable_keymap=1
  nmap <buffer> gd <plug>DeopleteRustGoToDefinitionDefault
  nmap <buffer> K <plug>DeopleteRustShowDocumentaion
'''
